[ci_cd]
jenkins-server ansible_host=35.238.12.89 ansible_user=devops

[monitoring]
prometheus-server ansible_host=34.60.151.118 ansible_user=devops

[app_nodes]
app-node-01 ansible_host=10.0.2.2 ansible_user=devops ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=devops@34.60.151.118'
app-node-02 ansible_host=10.0.2.3 ansible_user=devops ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=devops@34.60.151.118'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'